In [2]:
import numpy as np

A = np.array([[-3,2,1],[6,-8,-2],[1,-1,-2]], float)
b = np.array([2,1,3], float)

def Eliminacion_DD(A,b):
    Matrix_a = np.insert(A, A.shape[0], b, 1)
    n = len(b)
    x_solucion = np.zeros_like(b)
    for j in range(n):
        for i in range(j+1, n):
            factor = Matrix_a[i,j] / Matrix_a[j,j]
            #print(factor)
            Matrix_a[i, 0:n+1] = Matrix_a[i, 0:n+1] - factor*Matrix_a[j,0:n+1]
    print(Matrix_a)
    for k in range(n-1, -1, -1):
        x_solucion[k] = (Matrix_a[k,n] - np.dot(Matrix_a[k, k+1:n], x_solucion[k+1:n])) / Matrix_a[k,k]
    return x_solucion

Eliminacion_DD(A, b)

[[-3.          2.          1.          2.        ]
 [ 0.         -4.          0.          5.        ]
 [ 0.          0.         -1.66666667  3.25      ]]


array([-2.15, -1.25, -1.95])

In [3]:
import numpy as np

A = np.array([[0,2,1],[6,-8,-2],[1,-1,-2]], float)
b = np.array([2,1,3], float)

def Eliminacion_DD(A,b):
    Matrix_a = np.insert(A, A.shape[0], b, 1)
    n = len(b)
    x_solucion = np.zeros_like(b)
    for j in range(n):
        print(j, Matrix_a[j], Matrix_a[j][0])
        if Matrix_a[j][0] == 0:
            print(0)
            copia = Matrix_a[j].copy()
            print(copia)
    for j in range(n):
        for i in range(j+1, n):
            factor = Matrix_a[i,j] / Matrix_a[j,j]
            #print(factor)
            Matrix_a[i, 0:n+1] = Matrix_a[i, 0:n+1] - factor*Matrix_a[j,0:n+1]
    print(Matrix_a)
    for k in range(n-1, -1, -1):
        x_solucion[k] = (Matrix_a[k,n] - np.dot(Matrix_a[k, k+1:n], x_solucion[k+1:n])) / Matrix_a[k,k]
    return x_solucion

Eliminacion_DD(A, b)

0 [0. 2. 1. 2.] 0.0
0
[0. 2. 1. 2.]
1 [ 6. -8. -2.  1.] 6.0
2 [ 1. -1. -2.  3.] 1.0
[[  0.   2.   1.   2.]
 [ nan -inf -inf -inf]
 [ nan  nan  nan  nan]]


C:\Users\Valery Monsalve\AppData\Local\Temp\ipykernel_16788\2734590532.py:18: RuntimeWarning: divide by zero encountered in scalar divide
  factor = Matrix_a[i,j] / Matrix_a[j,j]
C:\Users\Valery Monsalve\AppData\Local\Temp\ipykernel_16788\2734590532.py:20: RuntimeWarning: invalid value encountered in multiply
  Matrix_a[i, 0:n+1] = Matrix_a[i, 0:n+1] - factor*Matrix_a[j,0:n+1]
C:\Users\Valery Monsalve\AppData\Local\Temp\ipykernel_16788\2734590532.py:18: RuntimeWarning: invalid value encountered in scalar divide
  factor = Matrix_a[i,j] / Matrix_a[j,j]


array([nan, nan, nan])