## Sitemas de ecuaciones lineales

In [15]:
import numpy as np

A = np.array([[-3,2,1],[6,-8,-2],[1,-1,-2]],float)
b = np.array([2,1,3],float)


matriz_a = np.insert(A, A.shape[0], b, 1)
x_solucion = np.zeros_like(b)

n = len(b)

for j in range(n):
    for i in range(j+1,n):
        factor = matriz_a[i,j]/matriz_a[j,j]
        matriz_a[i, 0:n+1] = matriz_a[i, 0:n+1] - factor*matriz_a[j, 0:n+1]

for k in range(n-1,- 1,-1):
    x_solucion[k] = (matriz_a[k,n]-np.dot(matriz_a[k,k+1:n],x_solucion[k+1:n]))/matriz_a[k,k]
print(x_solucion)


[-2.15 -1.25 -1.95]


In [16]:
import numpy as np

A = np.array([[-3,2,1],[6,-8,-2],[1,-1,-2]],float)
b = np.array([2,1,3],float)

def Eliminacion_DD(A,b):
    matriz_a = np.insert(A, A.shape[0], b, 1)
    x_solucion = np.zeros_like(b)

    n = len(b)

    for j in range(n):
        for i in range(j+1,n):
            factor = matriz_a[i,j]/matriz_a[j,j]
            matriz_a[i, 0:n+1] = matriz_a[i, 0:n+1] - factor*matriz_a[j, 0:n+1]

    for k in range(n-1,- 1,-1):
        x_solucion[k] = (matriz_a[k,n]-np.dot(matriz_a[k,k+1:n],x_solucion[k+1:n]))/matriz_a[k,k]
    return x_solucion
        


In [17]:
import numpy as np

A = np.array([[-3,2,1],[6,-8,-2],[1,-1,-2]],float)
b = np.array([2,1,3],float)

def Eliminacion_DD(A,b):
    matriz_a = np.insert(A, A.shape[0], b, 1)
    x_solucion = np.zeros_like(b)

    n = len(b)

    for j in range(n):
        for i in range(j+1,n):
            factor = matriz_a[i,j]/matriz_a[j,j]
            matriz_a[i, 0:n+1] = matriz_a[i, 0:n+1] - factor*matriz_a[j, 0:n+1]

    for k in range(n-1,- 1,-1):
        x_solucion[k] = (matriz_a[k,n]-np.dot(matriz_a[k,k+1:n],x_solucion[k+1:n]))/matriz_a[k,k]
    return x_solucion

Eliminacion_DD(A,b)

array([-2.15, -1.25, -1.95])

In [18]:
import numpy as np

A = np.array([[0,2,1],[6,0,-2],[1,-1,-2]],float)
b = np.array([2,1,3],float)

def Eliminacion_con_pivote(A,b):
    matriz_a = np.insert(A, A.shape[0], b, 1)
    x_solucion = np.zeros_like(b)

    n = len(b)


    for j in range(n):
        # Cambiar a mover a el condicional por fuera para hacer cambio
        # de los elementos en la diagonal donde son 0
        if matriz_a[j,j] == 0:
            copia_actual = matriz_a[j:n+1]
            print(matriz_a[j])
            matriz_a[j] = matriz_a[0:n+1]
            matriz_a[j+1]= copia_actual
            

        for i in range(j+1,n): 
            factor = matriz_a[i,j]/matriz_a[j,j]
            matriz_a[i, 0:n+1] = matriz_a[i, 0:n+1] - factor*matriz_a[j, 0:n+1]

    for k in range(n-1,- 1,-1):
        x_solucion[k] = (matriz_a[k,n]-np.dot(matriz_a[k,k+1:n],x_solucion[k+1:n]))/matriz_a[k,k]
    return x_solucion

#Eliminacion_con_pivote(A,b)

In [19]:
B = np.array([[-1,2,0],[2,-3,1],[0,1,2]],float)
eigvalues, eigvector = np.linalg.eig(B)
radio_espectral = max(abs(eigvalues))
print(eigvalues)
print(radio_espectral)

[-4.35109345  0.10219552  2.24889793]
4.351093446396054
