## Sistemas De Ecuaciones Lineales

In [1]:
import numpy as np

A = np.array([[-3,2,1],[6,-8,-2],[1,-1,-2]],float)
b = np.array([2,1,3],float)
n = len(b)

for i in range(n):
    for j in range(i+1,n):
        factor = A[j,i]/A[i,i]
        A[j,i:n] = A[j,i:n]-factor*A[i,i:n]
        b[j] = b[j] - factor*b[j - 1]
        if i == len(b):
            i = 0
        print(f"{A} and {b} \n")


[[-3.  2.  1.]
 [ 0. -4.  0.]
 [ 1. -1. -2.]] and [2. 5. 3.] 

[[-3.          2.          1.        ]
 [ 0.         -4.          0.        ]
 [ 0.         -0.33333333 -1.66666667]] and [2.         5.         4.66666667] 

[[-3.          2.          1.        ]
 [ 0.         -4.          0.        ]
 [ 0.          0.         -1.66666667]] and [2.   5.   4.25] 

